const API = window.BACKEND_URL || location.origin;
const $ = (id) => document.getElementById(id);
let token = localStorage.getItem('token') || '';
let role = localStorage.getItem('role') || '';
let stations = [];
let socket = null;
let currentStationId = null;
let selectedOrigin = null;
let selectedDestination = null;

function headers(json = false) { const h = json ? { 'Content-Type': 'application/json' } : {}; if (token) h.Authorization = `Bearer ${token}`; return h; }
function message(text, ok=false) { const el=$('authMessage'); if(el){el.textContent=text||'';el.style.color=ok?'#6ee7b7':'#ff9b9b';} }
function show(name) { document.querySelectorAll('.view').forEach(v => v.hidden = true); const view=$(name); if(view)view.hidden=false; document.querySelectorAll('.tabs-nav button').forEach(b=>b.classList.remove('active')); const map={overview:'homeTab',planner:'plannerTab',room:'roomTab',admin:'adminTab'}; if(map[name]&&$(map[name]))$(map[name]).classList.add('active'); }
function saveAuth(data) { token=data.token; role=data.role; localStorage.setItem('token',token); localStorage.setItem('role',role); }
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}

async function api(path, options={}) { const res=await fetch(`${API}${path}`,{...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}}); const data=await res.json().catch(()=>({})); if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`); return data; }
function normalizeStations(list){return Array.isArray(list)?list.slice().sort((a,b)=>String(a.line).localeCompare(String(b.line))||Number(a.order)-Number(b.order)):[];}
function renderTotals(){ $('stationTotal').textContent=stations.length; $('lineTotal').textContent=new Set(stations.map(s=>s.line)).size; }
function fillGovernors(){const vals=[...new Set(stations.map(s=>s.governorate).filter(Boolean))].sort();$('govSelect').innerHTML='<option value="">Select governorate</option>'+vals.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');$('citySelect').innerHTML='<option value="">Select city</option>';$('citySelect').disabled=true;$('originSelect').innerHTML='<option value="">Select station</option>';$('originSelect').disabled=true;}
function fillCities(){const g=$('govSelect').value;const vals=[...new Set(stations.filter(s=>s.governorate===g).map(s=>s.city).filter(Boolean))].sort();$('citySelect').innerHTML='<option value="">Select city</option>'+vals.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');$('citySelect').disabled=!g||!vals.length;$('originSelect').innerHTML='<option value="">Select station</option>';$('originSelect').disabled=true;}
function fillOrigins(){const g=$('govSelect').value,c=$('citySelect').value;const items=stations.filter(s=>s.governorate===g&&s.city===c).sort((a,b)=>a.order-b.order);$('originSelect').innerHTML='<option value="">Select station</option>'+items.map(s=>`<option value="${escapeHtml(String(s._id))}">${escapeHtml(s.name)} — ${escapeHtml(s.line)}</option>`).join('');$('originSelect').disabled=!items.length;}
async function refreshStations(silent=false){try{stations=normalizeStations(await api('/api/v1/stations'));renderTotals();fillGovernors();if(!silent)$('systemText').textContent=`Loaded ${stations.length} stations from the live database.`;renderAdmin();if(currentStationId)refreshRoom();}catch(e){$('systemText').textContent=e.message;}}
function connect(){if(!token)return;if(socket)socket.disconnect();socket=io(API,{auth:{token},transports:['websocket','polling']});socket.on('onlineCount',n=>{$('onlineTotal').textContent=Number(n||0);renderAdmin();});socket.on('presenceUpdate',({stationId,count})=>{if(currentStationId&&String(stationId)===String(currentStationId))$('roomCount').textContent=Number(count||0);renderAdmin();});socket.on('announcement',item=>{if(currentStationId&&String(item.stationId||'')===String(currentStationId))appendAnnouncement(item,true);});socket.on('stationsUpdated',()=>refreshStations(true));socket.on('connect_error',e=>{if(role) $('systemText').textContent=`Live connection unavailable: ${e.message}`;});}
function appendAnnouncement(item,top=false){const box=$('announcements');if(!box)return;const el=document.createElement('div');el.innerHTML=`<strong>📢 ${escapeHtml(item.message)}</strong><br><small>${item.createdAt?new Date(item.createdAt).toLocaleString():''}</small>`;top?box.prepend(el):box.appendChild(el);}
async function loadAnnouncements(){if(!currentStationId)return;const data=await api(`/api/v1/stations/${encodeURIComponent(currentStationId)}/announcements?limit=20`);$('announcements').innerHTML='';(data.items||[]).reverse().forEach(x=>appendAnnouncement(x));}
async function refreshRoom(){if(!currentStationId)return;const s=stations.find(x=>String(x._id)===String(currentStationId));if(!s)return;$('roomStationName').textContent=s.name;$('roomLine').textContent=s.line;$('roomDestination').textContent=selectedDestination?.name||'—';try{await loadAnnouncements();}catch(e){$('roomMessage').textContent=e.message;}}
function renderAdmin(){if(role!=='admin')return;const rows=stations.map(s=>`<div class="station-row"><strong>${escapeHtml(s.name)}</strong><span>${escapeHtml(s.line)}</span><span>${escapeHtml(s.governorate)}</span><span>${escapeHtml(s.city)}</span><div class="station-actions"><button type="button" data-edit="${escapeHtml(String(s._id))}">Edit</button><button type="button" data-del="${escapeHtml(String(s._id))}">Delete</button><button type="button" data-ann="${escapeHtml(String(s._id))}">Announce</button></div></div>`).join('');$('adminStations').innerHTML=rows||'<p>No stations.</p>';$('adminStats').innerHTML=`<article><small>Stations</small><strong>${stations.length}</strong></article><article><small>Lines</small><strong>${new Set(stations.map(s=>s.line)).size}</strong></article><article><small>Online</small><strong>${$('onlineTotal').textContent}</strong></article>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editStation(b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteStation(b.dataset.del));document.querySelectorAll('[data-ann]').forEach(b=>b.onclick=()=>postAnnouncement(b.dataset.ann));}
async function editStation(id){const s=stations.find(x=>String(x._id)===String(id));if(!s)return;const name=prompt('Station name',s.name);if(name===null)return;const city=prompt('City',s.city);if(city===null)return;const gov=prompt('Governorate',s.governorate);if(gov===null)return;const line=prompt('Line',s.line);if(line===null)return;const orderRaw=prompt('Order',s.order);if(orderRaw===null)return;const order=Number(orderRaw);if(!Number.isInteger(order)||order<1)return alert('Order must be a positive integer.');const arrival=prompt('Arrival HH:MM',s.arrivalTime||'00:00');if(arrival===null)return;const departure=prompt('Departure HH:MM',s.departureTime||'00:05');if(departure===null)return;await api(`/api/v1/stations/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({name:name.trim(),line:line.trim(),order,governorate:gov.trim(),city:city.trim(),arrivalTime:arrival.trim(),departureTime:departure.trim()})});await refreshStations();}
async function deleteStation(id){if(!confirm('Delete this station?'))return;await api(`/api/v1/stations/${encodeURIComponent(id)}`,{method:'DELETE'});if(String(currentStationId)===String(id))leaveRoom();await refreshStations();}
async function postAnnouncement(id){const text=prompt('Announcement message');if(!text||!text.trim())return;await api(`/api/v1/stations/${encodeURIComponent(id)}/announcements`,{method:'POST',body:JSON.stringify({message:text.trim()})});if(String(currentStationId)===String(id))await loadAnnouncements();}
async function addStation(){const name=prompt('Station name');if(!name)return;const line=prompt('Line','Line 1');if(line===null)return;const orderRaw=prompt('Order','1');if(orderRaw===null)return;const order=Number(orderRaw);if(!Number.isInteger(order)||order<1)return alert('Order must be a positive integer.');const governorate=prompt('Governorate','Cairo');if(governorate===null)return;const city=prompt('City','Cairo');if(city===null)return;const arrivalTime=prompt('Arrival','00:00');if(arrivalTime===null)return;const departureTime=prompt('Departure','00:05');if(departureTime===null)return;await api('/api/v1/stations',{method:'POST',body:JSON.stringify({name:name.trim(),line:line.trim(),order,governorate:governorate.trim(),city:city.trim(),arrivalTime:arrivalTime.trim(),departureTime:departureTime.trim()})});await refreshStations();}
function openPlanner(){show('planner');$('journeyStep1').hidden=false;$('journeyStep2').hidden=true;$('stepPill').textContent='Step 1 of 3';fillGovernors();}
function openDestination(){selectedOrigin=stations.find(s=>String(s._id)===$('originSelect').value);if(!selectedOrigin)return message('Choose an origin station first.');const dests=stations.filter(s=>s.line===selectedOrigin.line&&String(s._id)!==String(selectedOrigin._id)).sort((a,b)=>a.order-b.order);$('destinationSelect').innerHTML='<option value="">Select destination</option>'+dests.map(s=>`<option value="${escapeHtml(String(s._id))}">${escapeHtml(s.name)} — ${escapeHtml(s.city)}</option>`).join('');$('journeyStep1').hidden=true;$('journeyStep2').hidden=false;$('stepPill').textContent='Step 2 of 3';}
function prepareDestination(){selectedDestination=stations.find(s=>String(s._id)===$('destinationSelect').value);$('journeyPreview').textContent=selectedDestination?`${selectedOrigin.name} → ${selectedDestination.name} · ${selectedOrigin.line}`:'Select a destination.';}
function joinRoom(){if(!selectedOrigin||!selectedDestination)return message('Select an origin and destination first.');currentStationId=String(selectedOrigin._id);if(socket)socket.emit('joinStation',currentStationId);$('roomStationName').textContent=selectedOrigin.name;$('roomLine').textContent=selectedOrigin.line;$('roomDestination').textContent=selectedDestination.name;$('roomMessage').textContent='You are now connected to this station waiting room.';show('room');refreshRoom();}
function leaveRoom(){if(socket)socket.emit('leaveStation');currentStationId=null;$('roomCount').textContent='0';$('announcements').innerHTML='';show('overview');}
async function login(e){e.preventDefault();try{const data=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});saveAuth(data);$('authView').hidden=true;$('appView').hidden=false;$('sessionBadge').textContent=role==='admin'?'Admin':'Passenger';$('logoutBtn').hidden=false;$('adminTab').hidden=role!=='admin';$('addAnnouncement').hidden=role!=='admin';$('welcomeTitle').textContent=role==='admin'?'MetroFlow Admin':'Welcome to MetroFlow';$('loginForm').reset();message('');connect();await refreshStations();show('overview');}catch(e){message(e.message);}}
async function signup(e){e.preventDefault();try{await api('/api/v1/auth/signup',{method:'POST',body:JSON.stringify({name:$('signupName').value.trim(),email:$('signupEmail').value.trim(),password:$('signupPassword').value})});$('signupForm').hidden=true;$('loginForm').hidden=false;$('loginTab').classList.add('active');$('signupTab').classList.remove('active');$('signupForm').reset();message('Account created. You can log in now.',true);}catch(e){message(e.message);}}
function logout(){socket?.disconnect();token='';role='';localStorage.removeItem('token');localStorage.removeItem('role');location.reload();}
$('loginTab').onclick=()=>{$('loginForm').hidden=false;$('signupForm').hidden=true;$('loginTab').classList.add('active');$('signupTab').classList.remove('active');message('');};$('signupTab').onclick=()=>{$('loginForm').hidden=true;$('signupForm').hidden=false;$('signupTab').classList.add('active');$('loginTab').classList.remove('active');message('');};$('loginForm').onsubmit=login;$('signupForm').onsubmit=signup;$('logoutBtn').onclick=logout;$('homeTab').onclick=()=>show('overview');$('plannerTab').onclick=openPlanner;$('roomTab').onclick=()=>currentStationId?show('room'):message('Join a waiting room first.');$('adminTab').onclick=()=>show('admin');$('govSelect').onchange=fillCities;$('citySelect').onchange=fillOrigins;$('nextDestination').onclick=openDestination;$('backStep1').onclick=openPlanner;$('destinationSelect').onchange=prepareDestination;$('openRoom').onclick=joinRoom;$('leaveRoom').onclick=leaveRoom;$('refreshRoom').onclick=refreshRoom;$('refreshPulse').onclick=()=>refreshStations();$('addStation').onclick=addStation;$('adminRefresh').onclick=()=>refreshStations();
window.refreshStations=refreshStations;window.refreshRoom=refreshRoom;window.refreshAdmin=renderAdmin;
if(token){$('authView').hidden=true;$('appView').hidden=false;$('sessionBadge').textContent=role==='admin'?'Admin':'Passenger';$('logoutBtn').hidden=false;$('adminTab').hidden=role!=='admin';$('addAnnouncement').hidden=role!=='admin';$('welcomeTitle').textContent=role==='admin'?'MetroFlow Admin':'Welcome to MetroFlow';connect();refreshStations();}
